name: Environment Variables

on: 
  push:
    branches: [ main ]
env: 
  APP_NAME: BBS

jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
    - name : BBS
      run: echo "Hello $APP_NAME"
    - name : Access secret keys
      run: echo ${{ secrets.DB_CONNECT_KEY }}
    
    
